{
 "title": "Alluxio Master File Ops Dashboard",
 "description": "Grafana Dashboard that shows counts for 4 types of Alluxio file operations: create file, create dir, delete path, total operations.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alluxio Master - Total Completed File Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Master_CreateFileOps + Master_CreateDirectoryOps + Master_DeletePathOps"
    }
   ]
  },
  {
   "title": "Alluxio Master - Create File Operations (Master_CreateFileOps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "Master_CreateFileOps" }
   ]
  },
  {
   "title": "Alluxio Master - Create Directory Operations (Master_CreateDirectoryOps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "Master_CreateDirectoryOps" }
   ]
  },
  {
   "title": "Alluxio Master - Delete Path Operations (Master_DeletePathOps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "Master_DeletePathOps" }
   ]
  }
 ]
}